Scaling down an app while constraints violated and lost tasks present
Summary:
Regression test for https://github.com/mesosphere/marathon/issues/4059 which was solved through https://github.com/mesosphere/marathon/pull/4530

Test passes on master, applied to 1.3.0 this integration test fails with
```
 *** 1 TEST FAILED ***
TaskLostIntegrationTest:

- Scaling down an app while constraints violated and lost tasks present *** FAILED *** (32 seconds, 764 milliseconds)
  java.lang.AssertionError: Waiting for event deployment_success to arrive took longer than 30 seconds. Give up.
```
which is exactly the behavior which is described in 4059.

Test Plan: sbt "integration:test-only mesosphere.marathon.integration.TaskLostIntegrationTest"

Reviewers: meichstedt, testjohannes

Reviewed By: meichstedt, testjohannes

Subscribers: jenkins, marathon-team

Differential Revision: https://phabricator.mesosphere.com/D54