Fixes missing plugin dependecy
Missing dependency: net.virtual-void#sbt-dependency-graph;0.5.1

> sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.5.1: not found

https://travis-ci.org/janisz/marathon/builds/178113608
```
0c5486c99eda2741266442004b465353626a3420 is the first bad commit
commit 0c5486c99eda2741266442004b465353626a3420
Author: Tim Harper <tharper@mesosphere.com>
Date:   Tue Nov 22 12:20:09 2016 -0800

    Lock plugin dependency versions and use SSL

    Summary:
    - Using SSL protects against DNS spoofing / man-in-the-middle attacks by validating the authenticity of the server from which an artifact is being downloaded
    - Setting specific plugin versions helps to improve compatibility with dependency management plugins such as Coursier

    Test Plan: - Blow away maven cache. With a fresh SBT instance, run test:compile and packaging steps

    Reviewers: jasongilanfarr

    Reviewed By: jasongilanfarr

    Subscribers: jasongilanfarr, marathon-team

    Differential Revision: https://phabricator.mesosphere.com/D205

:100644 100644 ee2fd6fe4b789cce998933fed3509ea6db8b226d 3e5ddb46d6bb030d33bd7971bd4d657f60cb7582 M	build.sbt
:040000 040000 008e178001378908c0c5cf7ab7e9d4923a14cd23 c38c43a69bc74cc5b2381d43c548e3191d344ebd M	project
```